### PR TITLE
Remove backslashes

### PR DESCRIPTION
**Pull request by ImedAdel**
`path.join()` returns a string with backslashes on Windows 10 (Node.js 10 and 12), which breaks the whole routing system. This commit is a hotfix for that.

### CODE REVIEW

**Comment by ImedAdel** [comment]
After reconsideration, using Gatsby's `createFilePath()` is a safer option for these edge cases.

**Comment by johno** [comment]
Thanks for the PR!

Yeah I think we could use [`joinPath`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-core-utils#joinpath) from `gatsby-core-utils`.

**Comment by rdela** [comment]
I opened #78 using `joinPath`, was this what you had in mind John? `develop` and `build` work fine for me but I am on Mac and not sure how else to test. Imed if you have time to test it out or weigh in I would appreciate it.

**Comment by ImedAdel** [comment]
@rdela Thank you for your help 😃, Unfortunately, the issue wasn't resolved.

2019-08-23 09_31_18-localhost_8000

**Comment by rdela** [comment]
Thanks for testing Imed. Just to be sure we are on the same page, did you [checkout my PR](https://help.github.com/en/articles/checking-out-pull-requests-locally) and use [yarn link](https://yarnpkg.com/lang/en/docs/cli/link/) or were you testing against current? If that is too much trouble don't worry I can test in a Windows VM this weekend.

**Comment by ImedAdel** [comment]
@rdela No problem :) I did exactly that, except the yarn link part, I just ran `yarn workspace gatsby-starter-documentation gatsby develop` after making sure that I'm on the correct branch.

**Comment by rdela** [comment]
Right I forgot about the workspace so no need for `yarn link` I suppose. I am getting inconsistent results in attempting to add some logging and test the `yarn workspace gatsby-starter-documentation gatsby develop` command or `yarn start`/`npm run start` which look like they should do the same thing.

That said, I'm confused why your screenshot has pages named `hello-world(-2-5)` instead of:

```
/\\customizing
/\\license
/\\getting-started
/\\motivation
/\\
```

Did you change the page names or is that what you see cloning the repo in a fresh directory and running `yarn && yarn start`?

**Comment by ImedAdel** [comment]
I think that's normal considering this

2019-08-24 10_19_19-docs

**Comment by rdela** [comment]
Oh gotcha yes that is correct files for `/examples/gatsby-starter-documentation/docs/`, I was looking in `/docs/`.  Clearly I will not be any help until I debug in a Windows VM. I think it has to be running the old code but I am not sure why.

**Comment by rdela** [comment]
Unfortunately my reasons for working on these PRs have evaporated. Sorry I was not able to help resolve this.

**Comment by johno** [comment]
Thanks!

**Pull request merged**
